---

# this task will copy and execute script at remote host, where remote host will listen on specific port
- name: Transfer and execute a script.
  copy: src=nc_script.sh  dest=/var  mode=0777

- name: Execute the script
  command: sh /var/nc_script.sh "{{item}}"
  with_items:
     - "{{master_listening_ports}}"
  
  register: output1

- debug:
    msg: "{{output1}}"

#- name: Check all port numbers are accessible from current host
#  hosts: localhost
#  wait_for:
#    port: "{{ item }}"
#    state: started         # Port should be open
#    delay: 0               # No wait before first check (sec)
#    timeout: 3             # Stop checking after timeout (sec)
#  register: ping
#  ignore_errors: yes
#  with_items:
#     - "{{master_listening_ports}}"

#- debug:
#    msg: "{{ping}}"

